Modifique tildes
Diana-Arciniegas-Cruz/Hyperblog pull request #1
Opened 2024-11-01 15:38 UTC by Diana-Arciniegas-Cruz

Yo me di cuenta de ese error hace rato

2024-11-01 15:46 UTC, javiladino requested changes
En vez de usar tildes directas, usa entidades HTML

2024-11-02 07:01 UTC, Diana-Arciniegas-Cruz commented
Cambios hechos, por favor hazme el merge.

2024-11-02 07:02 UTC, javiladino commented
Excelente!

2024-11-02 07:02 UTC, javiladino commented
Lo cerré por error

2024-11-02 07:03 UTC, javiladino approved these changes
Perfecto

2024-11-02 07:05 UTC, merged